-- MySQL Script generated by MySQL Workbench
-- 06/18/15 10:38:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbLanchonete
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbLanchonete` ;

-- -----------------------------------------------------
-- Schema dbLanchonete
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbLanchonete` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbLanchonete` ;

-- -----------------------------------------------------
-- Table `dbLanchonete`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLanchonete`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `dbLanchonete`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(20) NULL,
  `data_nascimento` DATE NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(20) NULL,
  `complemento` VARCHAR(80) NULL,
  `ponto_referencia` VARCHAR(50) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLanchonete`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLanchonete`.`Produto` ;

CREATE TABLE IF NOT EXISTS `dbLanchonete`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `descricao_produto` VARCHAR(35) NULL,
  `valor` DECIMAL(10,2) NULL,
  `observacoes` VARCHAR(50) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLanchonete`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLanchonete`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `dbLanchonete`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NULL,
  `idCliente` INT NULL,
  `idProduto` INT NULL,
  `observacoes` VARCHAR(45) NULL,
  `data_pedido` DATE NULL,
  `total` DECIMAL(10,2) NULL,
  `quantia_receber` DECIMAL(10,2) NULL,
  `troco` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `PedCli_idx` (`idCliente` ASC),
  INDEX `PedPro_idx` (`idProduto` ASC),
  CONSTRAINT `PedCli`
    FOREIGN KEY (`idCliente`)
    REFERENCES `dbLanchonete`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PedPro`
    FOREIGN KEY (`idProduto`)
    REFERENCES `dbLanchonete`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLanchonete`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLanchonete`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `dbLanchonete`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
