/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import dao.BDMySQL;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;



/**
 *
 * @author sala306b
 */
public class FramePrincipal extends javax.swing.JFrame {
    FramePrincipal fp;
   
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
      
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        abreTela();
        
    }

   

//    public JDesktopPane getArea_trabalho() {
//        return area_trabalho;
//    }

  

    public JMenu getCadastros() {
        return cadastros;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JMenuItem getjMenuItem4() {
        return jMenuItem4;
    }

    public JMenuItem getmAjuda() {
        return mAjuda;
    }

    public JMenuItem getmAniversarios() {
        return mAniversarios;
    }

    public JMenuItem getmCadastroClientes() {
        return mCadastroClientes;
    }

    public JMenuItem getmCadastroProdutos() {
        return mCadastroProdutos;
    }

    public JMenuItem getmNovoPedido() {
        return mNovoPedido;
    }

    public JMenuItem getmNovoUsuario() {
        return mNovoUsuario;
    }

    public JMenuItem getmSair() {
        return mSair;
    }

    public JMenu getMenu() {
        return menu;
    }

    public JMenu getPedidos() {
        return pedidos;
    }

    public JDesktopPane getArea() {
        return area;
    }

    public void setArea(JDesktopPane area) {
        this.area = area;
    }

    
  
 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuItem4 = new javax.swing.JMenuItem();
        area = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mNovoUsuario = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenuItem();
        mAniversarios = new javax.swing.JMenuItem();
        mSair = new javax.swing.JMenuItem();
        cadastros = new javax.swing.JMenu();
        mCadastroClientes = new javax.swing.JMenuItem();
        mCadastroProdutos = new javax.swing.JMenuItem();
        pedidos = new javax.swing.JMenu();
        mNovoPedido = new javax.swing.JMenuItem();

        jButton2.setText("jButton2");

        jLabel2.setText("jLabel2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrega Rápida software");
        setBackground(new java.awt.Color(207, 230, 250));

        area.setToolTipText("");

        jLabel1.setText("jLabel1");

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/aa.jpeg"))); // NOI18N

        javax.swing.GroupLayout areaLayout = new javax.swing.GroupLayout(area);
        area.setLayout(areaLayout);
        areaLayout.setHorizontalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        areaLayout.setVerticalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(982, 982, 982))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        area.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        area.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/list.png"))); // NOI18N
        menu.setText("Menu");

        mNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add_user (1)_1.png"))); // NOI18N
        mNovoUsuario.setText("Novo usuário");
        menu.add(mNovoUsuario);

        mAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/system_help_1.png"))); // NOI18N
        mAjuda.setText("Ajuda");
        mAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAjudaActionPerformed(evt);
            }
        });
        menu.add(mAjuda);

        mAniversarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/balloons.png"))); // NOI18N
        mAniversarios.setText("Aniversáriantes");
        mAniversarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAniversariosActionPerformed(evt);
            }
        });
        menu.add(mAniversarios);

        mSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logout.png"))); // NOI18N
        mSair.setText("Sair");
        mSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSairActionPerformed(evt);
            }
        });
        menu.add(mSair);

        jMenuBar1.add(menu);

        cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sign_up (1).png"))); // NOI18N
        cadastros.setText("Cadastros");

        mCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/user_group_1.png"))); // NOI18N
        mCadastroClientes.setText("Cadastro de Clientes");
        cadastros.add(mCadastroClientes);

        mCadastroProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/hamburger (1)_1.png"))); // NOI18N
        mCadastroProdutos.setText("Cadastro de Produtos");
        cadastros.add(mCadastroProdutos);

        jMenuBar1.add(cadastros);

        pedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/order_159.png"))); // NOI18N
        pedidos.setText("Pedidos");

        mNovoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add_2.png"))); // NOI18N
        mNovoPedido.setText("Novo Pedido");
        pedidos.add(mNovoPedido);

        jMenuBar1.add(pedidos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(area)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(area, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mSairActionPerformed

    private void mAniversariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAniversariosActionPerformed
        // TODO add your handling code here:
//        FrameAniversario aniframe = new FrameAniversario();
//        area_trabalho.add(aniframe);
//        aniframe.setVisible(true);
    }//GEN-LAST:event_mAniversariosActionPerformed

    private void mAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mAjudaActionPerformed

  

// lookandfeel muda de cores
// biblioteca     looksdemo-2.3.1.jar

          //SkyBlue()
         //BrownSugar()
         // DarkStar()  
        //DesertGreen()
        //Silver()
        //ExperienceRoyale()
//     public void abreTela(){
//            
//            PlasticLookAndFeel.setPlasticTheme(new ExperienceBlue());
//                  try {
//                      UIManager.setLookAndFeel("com.jgoodies.looks.plastic.Plastic3DLookAndFeel");
//                  } catch (InstantiationException ex) {
//                      Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
//                  } catch (IllegalAccessException ex) {
//                      Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
//                  } catch (UnsupportedLookAndFeelException ex) {
//                      Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
//                  } catch (ClassNotFoundException ex) {
//            ex.printStackTrace();
//        }
//    SwingUtilities.updateComponentTreeUI(this);
//    
//     area.setBackground(Color.BLACK);
//
//}
//     

  /**
     * @param args the command line arguments
     */
    public void abreTela(){
        /*Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane area;
    private javax.swing.JMenu cadastros;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mAjuda;
    private javax.swing.JMenuItem mAniversarios;
    private javax.swing.JMenuItem mCadastroClientes;
    private javax.swing.JMenuItem mCadastroProdutos;
    private javax.swing.JMenuItem mNovoPedido;
    private javax.swing.JMenuItem mNovoUsuario;
    private javax.swing.JMenuItem mSair;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu pedidos;
    // End of variables declaration//GEN-END:variables

    
}
